### PR TITLE
Issue19 - Updating installation instructions

### LINKED ISSUE #19: Update installation instructions to reflect current repo.
The *Installation* section of the documentation instructs users to clone an obsolete version of the tool from:
``` 
git@github.com:HumanCellAtlas/ingest-graph-validator.git
``` 

The location of the repo in the documentation should be updated to:
``` 
git@github.com:ebi-ait/ingest-graph-validator.git
```

### PR DESCRIPTION
**Pull request by rays22**
Updating installation instructions to reflect current repo.
Fixes #19 

### Test plan

- [ ] Check that you have pulled the correct (`ebi-ait` forked) github version of the tool and the test set.
- [ ] Follow the updated installation instructions to check if everything works all right.

### CODE REVIEW

**Comment by rays22** [comment]
I have updated some URI references in the `README.md` document to reflect the current repo.
Also clarified a sentence in the test instructions.

**Comment by rays22** [comment]
Hi @aaclan-ebi ,
Could you kindly check if the documentation updates in this pull request look OK?
Thanks.

**Review by aaclan-ebi — APPROVED** [review]
Looks good! Thanks for making the changes!

**Comment by aaclan-ebi** [comment]
I'll merge this now as I want to push changes on top of this.

**Pull request merged**
