### PR TITLE
Fixed sequence_file to cell_suspensions test

### PR DESCRIPTION
**Pull request by ESapenaVentura**
Related to #8 

Now only checks for not-cell suspension --> sequence file when:

- Nucleic acid source is "single cell"
- File is a sequence file

### CODE REVIEW

**Comment by ESapenaVentura** [comment]
To test I used a normal spreadsheet and a modified version of one of the example spreadsheets:
[TEST_10x_generic.xlsx](https://github.com/ebi-ait/ingest-graph-validator/files/6285653/TEST_10x_generic.xlsx)

**Comment by mshadbolt** [comment]
Will this test fail if we start having `cell_suspension` --> `analysis_file` for projects where we can't publish raw data?

**Comment by ESapenaVentura** [comment]
It shouldn't because the path is targeting is the ones that include sequence files!

**Comment by mshadbolt** [comment]
ok cool, I think this will fix the error I identified but I think maybe sometime we have single cell projects that go direct from specimen to cell suspension when the specimen is blood?

**Comment by ESapenaVentura** [comment]
I thought we were modelling it as specimen --> cell suspension even if there was no dissociation/enrichment? at least that's how I've been modelling it every time

**Comment by mshadbolt** [comment]
Yeah I do the same as you, but I think there are some projects that have that specimen-> cell suspension linking

**Review by mshadbolt — APPROVED** [review]
I think this is an improvement to the test, the small exception is better to be caught and ignored because it is pretty rare.

**Comment by ESapenaVentura** [comment]
I just noticed I should also include "single nuclei" in the test

**Pull request merged**
